/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE ecografiaBaseService PLEASE EDIT ../ecografia.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Ecografia } from '../../domain/informe-de-imagenes_db/ecografia';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Ecografia.service.ts
 */

/*
 * SCHEMA DB Ecografia
 *
	{
		type: {
			type: 'String',
			required : true,
			enum : ["abdominal", "obstetrica"]
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_UserEcografia: {
			type: Schema.ObjectId,
			ref : "User"
		},
	}
 *
 */
@Injectable()
export class EcografiaBaseService {

    contextUrl: string = environment.endpoint + '/ecografia';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * EcografiaService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Ecografia): Observable<Ecografia> {
        return this.http
            .post<Ecografia>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * EcografiaService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * EcografiaService.findBytype
    *   @description CRUD ACTION findBytype
    *
    */
    findByType(id: string): Observable<Ecografia[]> {
        return this.http
            .get<Ecografia[]>(this.contextUrl + '/findBytype/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * EcografiaService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Ecografia> {
        return this.http
            .get<Ecografia>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * EcografiaService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Ecografia[]> {
        return this.http
            .get<Ecografia[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * EcografiaService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Ecografia): Observable<Ecografia> {
        return this.http
            .post<Ecografia>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
